[package]
name = "mining_proxy_sv2"
version = "0.1.0"
authors = ["user"]
edition = "2018"
description = "SV2 mining proxy role"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"

[dependencies]
async-channel = "1.8.0"
async-recursion = "0.3.2"
binary_sv2 = { version = "^0.1.6", path = "../../../protocols/v2/binary-sv2/binary-sv2" }
buffer_sv2 = { version = "^0.1.2", path = "../../../utils/buffer" }
codec_sv2 = { version = "0.1", path = "../../../protocols/v2/codec-sv2", features = ["noise_sv2", "with_buffer_pool"] }
const_sv2 = { version = "^0.1.2", path = "../../../protocols/v2/const-sv2" }
futures = "0.3.19"
network_helpers = {version = "^0.1.0", path = "../../../utils/network-helpers", features = ["with_tokio","with_buffer_pool"] }
once_cell = "1.12.0"
roles_logic_sv2 = { version = "^0.1.0", path = "../../../protocols/v2/roles-logic-sv2" }
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false }
tokio = { version = "1", features = ["full"] }
toml = { version = "*", git = "https://github.com/diondokter/toml-rs", default-features = false, rev = "c4161aa" }
tracing = {version = "0.1"}
tracing-subscriber = {version = "0.3"}
