[package]
name = "common_messages_sv2"
version = "0.1.6"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2 subprotocol common messages"
license = "MIT"
repository = "https://github.com/stratum-mining/stratum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.89", default-features = false, optional= true }
binary_sv2 = {version = "^0.1.6", path = "../../../../protocols/v2/binary-sv2/binary-sv2" }
const_sv2 = {version = "^0.1.2", path = "../../../../protocols/v2/const-sv2"}
quickcheck = { version = "1.0.3", optional=true }
quickcheck_macros = { version = "1", optional=true }
serde_repr = {version= "0.1.10", optional=true}

[features]
with_serde = ["binary_sv2/with_serde", "serde", "serde_repr"]
prop_test = ["quickcheck"]
