[package]
name = "binary_sv2"
version = "0.1.6"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2 data format"
license = "MIT"
repository = "https://github.com/stratum-mining/stratum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_sv2 = {version = "^0.1.2", path = "../serde-sv2", optional = true}
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false, optional = true }
binary_codec_sv2 = {version = "^0.1.4", path = "../no-serde-sv2/codec", optional = true}
derive_codec_sv2 = {version = "^0.1.4", path = "../no-serde-sv2/derive_codec", optional = true}
tracing = {version = "0.1"}

[features]
default = ["core"]
core = ["binary_codec_sv2", "derive_codec_sv2"]
with_serde = ["serde_sv2", "serde"]
prop_test = ["binary_codec_sv2/prop_test", "derive_codec_sv2"]
with_buffer_pool = ["binary_codec_sv2/with_buffer_pool", "derive_codec_sv2"]
