[package]
name = "noise_sv2"
version = "0.1.2"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2 noise"
license = "MIT"
repository = "https://github.com/stratum-mining/stratum"
# remove when git repo based dependencies are removed
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snow = "=0.9.1"
# TODO use crates.io repo as soon as a new version is issued (version 1.0.1 is not wirking)
ed25519-dalek = { git = "https://github.com/dalek-cryptography/ed25519-dalek", branch = "develop", commit = "431e699", features = ["rand", "serde", "alloc", "u64_backend"], default-features = false }
bs58 = { version ="0.4.0", features = ["check"] }
serde_json = { version = "1.0.64", default-features = false, features = ["alloc"] }
bytes = "1.0.1"
serde = { version = "1.0.89", features = ["derive"], default-features = false }
rand = "0.7.3" 
const_sv2 = {version = "^0.1.2", path = "../../../protocols/v2/const-sv2"}
buffer_sv2 = {version = "^0.1.2", path = "../../../utils/buffer"}
binary_sv2 = { version = "^0.1.6", path = "../../../protocols/v2/binary-sv2/binary-sv2" }
tracing = { version = "0.1"}

[features]
with_serde = ["binary_sv2/with_serde"]
